version: "3.7"

services:
  fastapp:
    build: fastapp
    ports:
      - 8000:8000
    networks:
      goalnetwork:
        aliases:
          - fastapp.docker
  streamlit:
    build: streamlit
    ports:
      - 8501:8501
    depends_on:
      - fastapp
    networks:
      goalnetwork:
        aliases:
          - streamlit.docker
networks:
  goalnetwork:
    external:
      name: "goalnetwork"
